# Generated by Django 4.1.8 on 2023-05-02 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=24)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidades', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detalles', models.TextField(max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='main/media/fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=20, unique=True)),
                ('gastosEnvio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('telefono', models.CharField(max_length=14)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.CharField(max_length=16)),
                ('titular', models.CharField(max_length=50)),
                ('cvv', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('fechaCaducidad', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, max_length=12)),
                ('unidades', models.IntegerField()),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=70)),
                ('localidad', models.CharField(max_length=20)),
                ('codPostal', models.IntegerField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.provincia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.direccion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='items',
            field=models.ManyToManyField(through='main.ItemCompra', to='main.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.metodopago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.perfil'),
        ),
    ]
